#!/bin/zsh
set -euo pipefail

project_dir="${0:A:h:h}"
worker="$project_dir/Sources/PodcastNotesApp/Resources/pipeline.py"
resources="$project_dir/Sources/PodcastNotesApp/Resources"
database="$HOME/Library/Application Support/PodcastNotes/podcast_notes.sqlite3"
lock_dir="$HOME/Library/Application Support/PodcastNotes/.daily-update.lock"
lock_pid="$lock_dir/pid"

mkdir -p "${database:h}"
if ! mkdir "$lock_dir" 2>/dev/null; then
  existing_pid=""
  if [[ -f "$lock_pid" ]]; then IFS= read -r existing_pid < "$lock_pid" || true; fi
  if [[ "$existing_pid" == <-> ]] && kill -0 "$existing_pid" 2>/dev/null; then
    echo "{\"status\":\"skipped\",\"reason\":\"another update is running\",\"pid\":$existing_pid}"
    exit 0
  fi
  rm -f "$lock_pid"
  rmdir "$lock_dir" 2>/dev/null || true
  if ! mkdir "$lock_dir" 2>/dev/null; then
    echo '{"status":"skipped","reason":"update lock could not be acquired"}'
    exit 0
  fi
fi
print -r -- "$$" > "$lock_pid"
trap 'rm -f "$lock_pid"; rmdir "$lock_dir" 2>/dev/null || true' EXIT INT TERM

python3 "$worker" --db "$database" --resources "$resources" init >/dev/null

# New sources whose automatic programme profile previously failed are retried
# here. Profiles are generated by Luna and never exposed as a user setting.
sqlite3 -noheader "$database" \
  "SELECT id FROM sources WHERE enabled=1 AND archived=0 AND health='profile_pending' ORDER BY created_at;" | \
while IFS= read -r source_id; do
  [[ -n "$source_id" ]] || continue
  python3 "$worker" --db "$database" --resources "$resources" source-profile "$source_id" || true
done

python3 "$worker" --db "$database" --resources "$resources" update \
  --trigger codex_schedule --lookback-days 30 --per-source 5 --retry-failed

# Persist bilingual reading data for every newly completed episode. This is a
# one-shot stage of the scheduled run; no process remains after the script exits.
sqlite3 -noheader "$database" "
  SELECT e.id FROM episodes e
  WHERE e.status='complete'
    AND EXISTS (
      SELECT 1 FROM transcript_segments t
      WHERE t.episode_id=e.id AND t.translated_text IS NULL
    )
  ORDER BY e.published_at DESC LIMIT 100;
" | while IFS= read -r episode_id; do
  [[ -n "$episode_id" ]] || continue
  python3 "$worker" --db "$database" --resources "$resources" translate "$episode_id"
done

sqlite3 -json "$database" "
  SELECT
    datetime('now') AS finished_at,
    (SELECT count(*) FROM sources WHERE enabled=1 AND archived=0) AS active_sources,
    (SELECT count(*) FROM episodes WHERE status='complete') AS complete_episodes,
    (SELECT count(*) FROM episodes WHERE status='no_transcript') AS no_transcript,
    (SELECT count(*) FROM episodes WHERE status='failed') AS failed;
"
